name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (skip submission and release)"
        required: false
        default: false
        type: boolean
      chrome:
        description: "Submit to Chrome Web Store"
        required: false
        default: true
        type: boolean
      firefox:
        description: "Submit to Firefox Add-ons"
        required: false
        default: true
        type: boolean
      github_release:
        description: "Create GitHub Release"
        required: false
        default: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Zip
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Submit to Chrome
        id: submit-chrome
        if: github.event_name == 'push' || inputs.chrome
        run: |
          pnpm wxt submit \
            --chrome-zip .output/*-chrome.zip \
            ${{ inputs.dry_run && '--dry-run' || '' }}
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Submit to Firefox
        id: submit-firefox
        if: github.event_name == 'push' || inputs.firefox
        run: |
          pnpm wxt submit \
            --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip \
            ${{ inputs.dry_run && '--dry-run' || '' }}
        env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: Upload to GitHub Release
        if: github.event_name == 'push' || inputs.github_release
        run: npx changelogithub --assets ".output/*-chrome.zip,.output/*-firefox.zip" ${{ inputs.dry_run && '--dry' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
